# Generated by Django 5.1.7 on 2025-05-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_election_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='candidates',
            field=models.ManyToManyField(related_name='election', to='home.candidate'),
        ),
    ]
