# Generated by Django 5.1.7 on 2025-05-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customuser_address_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='citizenship_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
