# Generated by Django 5.1.7 on 2025-05-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customuser_citizenship_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fathers_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mothers_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
