# Generated by Django 5.1.7 on 2025-05-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customuser_fathers_name_customuser_mothers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fathers_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mothers_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
